#include "descriptors_wrapper.h"


/*
DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_improved, get_msurf_descriptor_improved)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_improved_flip, get_msurf_descriptor_improved_flip)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_improved_flip_flip, get_msurf_descriptor_improved_flip_flip)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_inlined, get_msurf_descriptor_inlined)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_gauss_s1_separable_test, get_msurf_descriptors_gauss_s1_separable_test)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_gauss_s2_precomputed, get_msurf_descriptor_gauss_s2_precomputed)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_inlinedHaarWavelets, get_msurf_descriptor_inlinedHaarWavelets)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_inlinedHaarWavelets_precheck_boundaries, get_msurf_descriptor_inlinedHaarWavelets_precheck_boundaries)

DEFINE_GET_MSURF_DESCRIPTORS(get_msurf_descriptors_gauss_compute_once_case, get_msurf_descriptor_gauss_compute_once_case)
*/
